<?xml version="1.0" encoding="UTF-8"?>
<definitions id="definitions" 
  xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:camunda="http://camunda.org/schema/1.0/bpmn"
  targetNamespace="Examples">
  
  <error id="myException" errorCode="org.camunda.bpm.engine.test.bpmn.event.error.MyBusinessException"/>
  
  <process id="testCatchExceptionThrownByExpressionOnServiceTask" isExecutable="true">
  
    <startEvent id="theStart" />
    <sequenceFlow id="flow1" sourceRef="theStart" targetRef="serviceTask" />
    
    <serviceTask id="serviceTask" camunda:expression="#{bpmnErrorBean.throwBpmnException()}" />
    
    <boundaryEvent id="catchException" attachedToRef="serviceTask">
      <errorEventDefinition errorRef="myException"/>
    </boundaryEvent>
    
    <sequenceFlow id="flow3" sourceRef="catchException" targetRef="escalatedExceptionTask" />
    
    <userTask id="escalatedExceptionTask" name="Escalated Exception Task" />
    <sequenceFlow id="flow4" sourceRef="serviceTask" targetRef="theEnd" />
    
    <endEvent id="theEnd" />
    
  </process>

</definitions>