<?xml version="1.0" encoding="UTF-8"?>
<definitions id="definitions" 
  xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
  xmlns:camunda="http://camunda.org/schema/1.0/bpmn"
  targetNamespace="Examples">
  
  <error id="myError" errorCode="23"/>
  <error id="myException" errorCode="org.camunda.bpm.engine.test.bpmn.event.error.MyBusinessException" />
  
  <process id="catchErrorThrownByJavaDelegateOnMultiInstanceServiceTaskSequential" isExecutable="true">
  
    <startEvent id="theStart" />
    <sequenceFlow id="flow1" sourceRef="theStart" targetRef="serviceTask" />
    
    <serviceTask id="serviceTask" camunda:class="org.camunda.bpm.engine.test.bpmn.event.error.ThrowBpmnErrorDelegate">
      <multiInstanceLoopCharacteristics isSequential="true">
        <loopCardinality>3</loopCardinality>
      </multiInstanceLoopCharacteristics>
    </serviceTask>
    
    <boundaryEvent id="catchError" attachedToRef="serviceTask">
      <errorEventDefinition errorRef="myError"/>
    </boundaryEvent>

    <boundaryEvent id="catchException" attachedToRef="serviceTask">
      <errorEventDefinition errorRef="myException"/>
    </boundaryEvent>
    
    <sequenceFlow id="flow3" sourceRef="catchError" targetRef="escalatedTask" />
    
    <sequenceFlow id="flow4" sourceRef="catchException" targetRef="escalatedExceptionTask" />
    
    <userTask id="escalatedTask" name="Escalated Task" />
    
    <userTask id="escalatedExceptionTask" name="Escalated Exception Task" />
    
    <sequenceFlow id="flow5" sourceRef="serviceTask" targetRef="theEnd" />
    
    <endEvent id="theEnd" />
    
  </process>

</definitions>